services:
  app:
    privileged: true
    container_name: nishinoya
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - ./.env:/app/.env