FROM python:3.11

RUN apt-get update && \
    apt-get install -y python3-pip ffmpeg && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN git clone 'https://github.com/dylanatianzar/NishinoyaBot.git'
WORKDIR /NishinoyaBot
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /NishinoyaBot/src

CMD ["python", "main.py"]
