FROM python:3.11

RUN apt-get update && \
    apt-get install -y python3-pip ffmpeg && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install -r requirements.txt
RUN git clone 'https://github.com/dylanatianzar/NishinoyaBot.git'

WORKDIR /app/src

CMD ["python", "main.py"]
